CREATE TABLE IF NOT EXISTS datasets (name TEXT PRIMARY KEY, body TEXT NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, cache_key TEXT NOT NULL, kind TEXT NOT NULL, context TEXT NOT NULL, status TEXT NOT NULL, progress TEXT NOT NULL DEFAULT '{}', result TEXT, created INTEGER NOT NULL, updated INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS jobs_status ON jobs(status,created);
CREATE INDEX IF NOT EXISTS jobs_cache ON jobs(cache_key,created);
CREATE TABLE IF NOT EXISTS counters (key TEXT PRIMARY KEY, n INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
