import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{normalizeContext,consume,currentTerm,taipeiDate} from '../worker/index.mjs';
class DB {
 constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('../worker/schema.sql',import.meta.url),'utf8'));}
 prepare(sql){let args=[];const db=this.db;return {bind(...v){args=v;return this;},async first(){return db.prepare(sql).get(...args)||null;},async run(){return db.prepare(sql).run(...args);},async all(){return {results:db.prepare(sql).all(...args)};}};}
 async batch(list){const out=[];for(const s of list)out.push(await s.run());return out;}
}
function env(){return {DB:new DB(),RUNNER_TOKEN:'r'.repeat(64),GH_DISPATCH_TOKEN:'test-not-a-secret',GITHUB_REPO:'owner/repo',GITHUB_BRANCH:'main',SEARCH_CONFIGURED:'true',AI:{run:async()=>({response:'{"ok":true}'})},ASSETS:{fetch:async()=>new Response('asset')}};}
const payload={schoolName:'Test University',term:'115-1',city:'',district:'',schoolUrl:'',noticeName:'',noticeUrl:'',gradeTerms:['114-1','114-2']};
const original=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:204});
async function req(e,path,body,auth=false,method){return worker.fetch(new Request('https://app.example'+path,{method:method||(body===undefined?'GET':'POST'),headers:{Origin:'https://app.example','Content-Type':'application/json',...(auth?{Authorization:'Bearer '+e.RUNNER_TOKEN}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})}),e);}
test('time boundaries use Taipei calendar',()=>{assert.equal(currentTerm(Date.parse('2026-08-01T00:00:00+08:00')),'115-1');assert.equal(currentTerm(Date.parse('2026-02-01T00:00:00+08:00')),'114-2');assert.equal(taipeiDate(Date.parse('2026-09-19T23:00:00Z')),'2026-09-20');});
test('never accept grades or income in search requests',()=>{for(const k of ['annualScore','economic','income','profile','__proto__']){const x=JSON.parse(JSON.stringify(payload));Object.defineProperty(x,k,{value:80,enumerable:true});assert.throws(()=>normalizeContext(x));}});
test('public URLs and district sanitization',()=>{assert.throws(()=>normalizeContext({...payload,noticeUrl:'http://127.0.0.1/a'}));assert.throws(()=>normalizeContext({...payload,noticeUrl:'https://a.example:999/a'}));assert.throws(()=>normalizeContext({...payload,city:'Taipei',district:'x'}));assert.deepEqual(normalizeContext(payload),payload);});
test('durable queue -> claim -> progress -> result',async()=>{const e=env();let r=await req(e,'/api/discovery',payload);assert.equal(r.status,202);const {jobId}=await r.json();assert.match(jobId,/^[a-f0-9]{32}$/);let c=await (await req(e,'/internal/claim',{},true)).json();assert.equal(c.job.id,jobId);assert.deepEqual(c.job.context,payload);await req(e,'/internal/job',{id:jobId,status:'done',progress:{stages:[{key:'inspect',status:'done'}]},result:{context:payload,outcome:'completed',candidates:[],stats:{added:1}}},true);let x=await (await req(e,'/api/jobs/'+jobId)).json();assert.equal(x.status,'done');assert.equal(x.result.stats.added,1);r=await req(e,'/api/discovery',payload);assert.equal((await r.json()).jobId,jobId);});
test('same origin and internal authentication enforced',async()=>{const e=env();assert.equal((await req(e,'/internal/claim',{})).status,401);const r=await worker.fetch(new Request('https://app.example/api/discovery',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify(payload)}),e);assert.equal(r.status,403);});
test('dataset write and read preserve structured data, no public private cache',async()=>{const e=env();await req(e,'/internal/dataset/library.json',{programs:[{id:'x'}]},true,'PUT');assert.equal((await (await req(e,'/data/library.json')).json()).programs[0].id,'x');assert.equal((await req(e,'/data/runner-meta.json')).status,404);});
test('daily job idempotent, forced run distinct',async()=>{const e=env();const a=await (await req(e,'/internal/daily',{},true)).json();const b=await (await req(e,'/internal/daily',{},true)).json();const c=await (await req(e,'/internal/daily',{force:true},true)).json();assert.equal(a.id,b.id);assert.notEqual(a.id,c.id);});
test('hard free quotas stop calls, not upgrade',async()=>{const e=env();for(let i=0;i<30;i++)assert.equal(await consume(e,'search'),true);assert.equal(await consume(e,'search'),false);for(let i=0;i<16;i++)assert.equal(await consume(e,'ai'),true);assert.equal(await consume(e,'ai'),false);assert.equal(await consume(e,'bad'),false);});
test('per-IP limiter rejects repeated unique requests',async()=>{const e=env();for(let i=0;i<3;i++)assert.equal((await req(e,'/api/discovery',{...payload,schoolName:'Uni '+i})).status,202);assert.equal((await req(e,'/api/discovery',{...payload,schoolName:'Fourth'})).status,429);});
test('diagnostics retain actual results and status exposes version',async()=>{const e=env();await req(e,'/internal/diagnostics',{ok:false,checks:[{name:'Live API',ok:false}]},true);const x=await(await req(e,'/api/status')).json();assert.equal(x.appVersion,14);assert.equal(x.diagnostics.ok,false);assert.equal(x.scheduler.localTime,'12:00');});
test('AI request path invokes binding and consumes limit',async()=>{const e=env();let calls=0;e.AI.run=async()=>{calls++;return {response:{ok:true}};};for(let i=0;i<16;i++)assert.equal((await req(e,'/internal/ai',{messages:[{role:'user',content:'test'}]},true)).status,200);assert.equal((await req(e,'/internal/ai',{messages:[]},true)).status,429);assert.equal(calls,16);});
test('stale running job requeued and continued without losing it',async()=>{const e=env();const {jobId}=await(await req(e,'/api/discovery',payload)).json();await req(e,'/internal/claim',{},true);await e.DB.prepare('UPDATE jobs SET updated=? WHERE id=?').bind(1,jobId).run();const c=await(await req(e,'/internal/claim',{},true)).json();assert.equal(c.job.id,jobId);assert.equal(c.job.attempts,2);});
